export const Colors = {
  primary: '#4A7BF7',
  primaryLight: '#6B9CFF',
  nodeBackground: '#FFFFFF',
  nodeLightBlue: '#EAF1FF',
  nodeSubDetail: '#F0F7FF',
  nodeBranch1: '#FFF7ED',
  nodeBranch2: '#F0FDF4',
  nodeBranch3: '#FDF2F8',
  nodeBranch4: '#FEF9C3',
  nodeBranch5: '#F5F3FF',
  nodeBorder: '#E2E8F0',
  connectionLine: '#94A3B8',
  addButton: '#4A7BF7',
  textDark: '#1E293B',
  textLight: '#64748B',
  headerBg: '#4A7BF7',
  headerText: '#FFFFFF',
  background: '#F8FAFC',
  shadow: 'rgba(0,0,0,0.06)',
};

export const NodeConfig = {
  rootWidth: 180,
  rootHeight: 48,
  rootRadius: 24,
  nodeWidth: 130,
  nodeHeight: 40,
  nodeRadius: 12,
  subNodeWidth: 120,
  subNodeHeight: 36,
  subNodeRadius: 10,
  addButtonSize: 20,
  horizontalGap: 45,
  verticalGap: 10,
};
